# Generated by Django 5.0.3 on 2024-03-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cook_time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.TextField(default='30 minutes'),
        ),
    ]
